#!/bin/bash

while true; do
  current_second=$(date +%S)
  if [ "$current_second" -ge 45 ]; then
    for i in {0..20000}; do
      echo Test2 $i
      sleep 0.0001
      echo "Test2 error $i" >&2
    done
    break
  else
    echo "wait2 exec $current_second"
    echo "wait2 exec $current_second" >&2
    sleep 1
  fi
done
